#pragma checksum "C:\Users\lzy\Documents\Source\LrcMaker\Opportunity.LrcMaker\Strings\zh-Hans\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D0CD2C6765F3227B4B6FB09A7BA82742"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Opportunity.LrcMaker.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.5.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
    }
}

namespace Opportunity.LrcMaker
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.5.0")]
    internal static class Strings
    {

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::Opportunity.LrcMaker.ResourceInfo.IResources Resources__C5QC9bXm;
        internal static global::Opportunity.LrcMaker.ResourceInfo.IResources Resources 
            => global::System.Threading.LazyInitializer.EnsureInitialized(ref Resources__C5QC9bXm, () => new global::Opportunity.LrcMaker.Strings.Resources___MBQcHGu());

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.5.0")]
        private sealed class Resources___MBQcHGu : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcMaker.ResourceInfo.IResources
        {
            public Resources___MBQcHGu() : base("ms-resource:///Resources/") { }


        }
    }
}
