#pragma checksum "C:\Users\lzy\Documents\Source\LrcMaker\Opportunity.LrcMaker\Strings\zh-Hans\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "0729233641C14EAD58AAB67C7D373B92"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Opportunity.LrcMaker.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.6.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::Opportunity.LrcMaker.ResourceInfo.Resources.IExtensions Extensions { get; }
    }
}

namespace Opportunity.LrcMaker.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.6.0")]
    internal interface IExtensions : global::Opportunity.ResourceGenerator.IResourceProvider
    {
#warning Resource has been renamed. ResourceName: "Aurora.Music.Extensions", PropertyName: "Aurora_Music_Extensions"
        global::Opportunity.LrcMaker.ResourceInfo.Resources.Extensions.IAurora_Music_Extensions Aurora_Music_Extensions { get; }
    }
}

namespace Opportunity.LrcMaker.ResourceInfo.Resources.Extensions
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.6.0")]
    internal interface IAurora_Music_Extensions : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Lrc Maker</para>
        /// </summary>
        string DisplayName { get; }
        /// <summary>
        /// <para>来自网易云音乐，ViewLyrics.com 和千千静听的歌词</para>
        /// </summary>
        string Description { get; }
    }
}

namespace Opportunity.LrcMaker
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.6.0")]
    internal static class Strings
    {

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::Opportunity.LrcMaker.ResourceInfo.IResources Resources__SkPf3Eq1;
        internal static global::Opportunity.LrcMaker.ResourceInfo.IResources Resources 
            => global::System.Threading.LazyInitializer.EnsureInitialized(ref Resources__SkPf3Eq1, () => new global::Opportunity.LrcMaker.Strings.Resources__s__ew_aL());

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.6.0")]
        private sealed class Resources__s__ew_aL : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcMaker.ResourceInfo.IResources
        {
            public Resources__s__ew_aL() : base("ms-resource:///Resources/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Opportunity.LrcMaker.ResourceInfo.Resources.IExtensions Extensions___rxTWQGf;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extensions")]
            global::Opportunity.LrcMaker.ResourceInfo.Resources.IExtensions global::Opportunity.LrcMaker.ResourceInfo.IResources.Extensions 
                => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Extensions___rxTWQGf, () => new global::Opportunity.LrcMaker.Strings.Resources__s__ew_aL.Extensions__rLEBRzj8());

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.6.0")]
            private sealed class Extensions__rLEBRzj8 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcMaker.ResourceInfo.Resources.IExtensions
            {
                public Extensions__rLEBRzj8() : base("ms-resource:///Resources/Extensions/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private global::Opportunity.LrcMaker.ResourceInfo.Resources.Extensions.IAurora_Music_Extensions Aurora_Music_Extensions__qChm_AK0;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extensions/Aurora.Music.Extensions")]
                global::Opportunity.LrcMaker.ResourceInfo.Resources.Extensions.IAurora_Music_Extensions global::Opportunity.LrcMaker.ResourceInfo.Resources.IExtensions.Aurora_Music_Extensions 
                    => global::System.Threading.LazyInitializer.EnsureInitialized(ref this.Aurora_Music_Extensions__qChm_AK0, () => new global::Opportunity.LrcMaker.Strings.Resources__s__ew_aL.Extensions__rLEBRzj8.Aurora_Music_Extensions__WvTlsb1t());

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.6.0")]
                private sealed class Aurora_Music_Extensions__WvTlsb1t : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::Opportunity.LrcMaker.ResourceInfo.Resources.Extensions.IAurora_Music_Extensions
                {
                    public Aurora_Music_Extensions__WvTlsb1t() : base("ms-resource:///Resources/Extensions/Aurora.Music.Extensions/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extensions/Aurora.Music.Extensions/DisplayName")]
                    string global::Opportunity.LrcMaker.ResourceInfo.Resources.Extensions.IAurora_Music_Extensions.DisplayName
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extensions/Aurora.Music.Extensions/DisplayName");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Extensions/Aurora.Music.Extensions/Description")]
                    string global::Opportunity.LrcMaker.ResourceInfo.Resources.Extensions.IAurora_Music_Extensions.Description
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Extensions/Aurora.Music.Extensions/Description");
                }

            }

        }
    }
}
